### ISSUE TITLE
failure Image modal navigation buttons still works irrespective of one test failure with screenshot

### ISSUE THREAD

**Issue by venkataramkishore** [Evilweed/protractor-beautiful-reporter#72] opened 2018-07-24 12:42 UTC
Hi Team,
Great work in using simple protractor tests.

I see the image modal navigation button **Prev** and **Next** are still available when there is only one test failure with a screenshot.
It rotates available tests with an empty block.

In config, I used below as true and expected to have only error screenshots
takeScreenShotsOnlyForFailedSpecs

**Comment by miller45** [comment] 2018-08-14 17:28
@venkataramkishore I can confirm that this a bug which occurs when takeScreenShotsOnlyForFailedSpecs is true. But it is not easy to fix because it is not just a glitch but a "missing implementation" which is quite complicated to do actually.

**Comment by miller45** [comment] 2019-08-22 14:23
@venkataramkishore This fixed in Version 1.3.0 (just released)

**Closed by miller45** 2019-08-22 14:23 UTC
Labels: bug
