### ISSUE TITLE
With many fails in test much are not reported

### ISSUE THREAD

**Issue by amedvedjev** [Evilweed/protractor-beautiful-reporter#60] opened 2018-05-08 08:12 UTC
test structure to reproduce:
```
describe() {
  beforeAll()
    it()
    it()
}
describe() {
  beforeAll()
    it()
    it()
}
... // same after
```

error in logs:
```
Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:28226
....
From: Task: WebDriver.manage().logs().get(browser)
    at Driver.schedule (D:\tc\ba2\work\a5d9398c7ec5eb82\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at Logs.get (D:\tc\ba2\work\a5d9398c7ec5eb82\node_modules\selenium-webdriver\lib\webdriver.js:1731:25)
    at Jasmine2Reporter._callee7$ (D:\tc\ba2\work\a5d9398c7ec5eb82\node_modules\protractor-beautiful-reporter\index.js:4897:64)
    at tryCatch (D:\tc\ba2\work\a5d9398c7ec5eb82\node_modules\protractor-beautiful-reporter\index.js:5377:40)
    at Generator.invoke [as _invoke] (D:\tc\ba2\work\a5d9398c7ec5eb82\node_modules\protractor-beautiful-reporter\index.js:5651:22)
    at Generator.prototype.(anonymous function) [as next] (D:\tc\ba2\work\a5d9398c7ec5eb82\node_modules\protractor-beautiful-reporter\index.js:5410:21)
    at step (D:\tc\ba2\work\a5d9398c7ec5eb82\node_modules\protractor-beautiful-reporter\index.js:4481:191)
    at D:\tc\ba2\work\a5d9398c7ec5eb82\node_modules\protractor-beautiful-reporter\index.js:4481:361

...
Error
    at Jasmine2Reporter.jasmineStarted (D:\tc\ba2\work\a5d9398c7ec5eb82\node_modules\protractor-beautiful-reporter\index.js:4691:13)
    at dispatch (D:\tc\ba2\work\a5d9398c7ec5eb82\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4366:28)
...
```

**Comment by Evilweed** [comment] 2018-05-10 09:46
@amedvedjev google before reporting issue. This issue is not caused by the reporter.

[https://github.com/nodejs/help/issues/434](https://github.com/nodejs/help/issues/434)
[https://github.com/angular/protractor/issues/4447](https://github.com/angular/protractor/issues/4447)

Closing.

**Closed by Evilweed** 2018-05-10 09:46 UTC
