### ISSUE TITLE
disable create screenshot (run tests without browser?)

### ISSUE THREAD

**Issue by rebajz** [Evilweed/protractor-beautiful-reporter#162] opened 2019-08-21 07:34 UTC
Now is possible set Screenshots only for failed test cases (true, false)

It is not possible set: never do screenshot.

Why is needed this option?

When tester need do something (for example preset test machine) befere running test in browser, each IT have this message> 
 - Failed: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:34830

**Comment by miller45** [comment] 2019-08-21 08:24
@rebajz duplicate of #153 if will see what I can do shortly

**Comment by miller45** [comment] 2019-08-21 10:40
@rebajz just a released the version 1.2.10 with the `disableScreenshots` option

**Comment by rebajz** [comment] 2019-08-22 06:18
thanks a lot

**Comment by rebajz** [comment] 2019-08-22 07:59
when running test without webdriver (chrome driver) - beatuful reportil still do  
Failed: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:34830

:-(

**Comment by miller45** [comment] 2019-08-22 08:29
You need a webdriver for protractor to work IMHO.
Which browser do you want to test? Firefox? Internet explorer?
The reporter is only for protractor e2e tests not for unit test

**Comment by rebajz** [comment] 2019-08-22 08:35
we testing CEF browser (chrome). But this cef browser running in windows app. Therefore we must first run this app and do some settings before is opened device with this cef browser.  For simple - some IT running without webdriver - contains only autoit code ( https://www.npmjs.com/package/autoit )

**Comment by miller45** [comment] 2019-08-22 08:42
I see...have tested this without the protractor-beautiful-reporter? with pure protractor e2e test? 
This reporter works only if tests are done via protractor any other case is not supported.

**Comment by miller45** [comment] 2019-08-22 08:46
@rebajz You should look into this article https://stackoverflow.com/questions/35114639/automation-test-of-angularjs-app-hosted-under-cefsharp-browser-in-wpf-by-using-p
It describes how to used protractor (or selenium) with cefsharp embedded browsers.

**Comment by rebajz** [comment] 2019-08-22 09:00
without beautiful protractor reporter everything running ok.  When i add code for beatuful reporter to my config, test running, but have IT as failed.

when i running different config file with same code for beautiful reporter, but with running webdriver, everything is OK.

**Comment by miller45** [comment] 2019-08-23 09:58
Can you provide your protractor configuration and a small example of you e2e test spec?
Do you run the tests with directconnect or via a selenium server?

**Comment by miller45** [comment] 2019-08-23 10:53
Did remove the line with 'jasmine.getEnv().clearReporters();' in the test without "beautiful reporter". 
Because if you leave the line "clearReporters()" you see no real tests results and then you cannot see any "IT" failing.

**Closed** 2019-09-05 09:53 UTC
Labels: support
